# Generated by Django 4.2.27 on 2025-12-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoparticipante',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción Evento', 'verbose_name_plural': 'Inscripciones Eventos'},
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado', models.CharField(default='CONFIRMADA', max_length=20, verbose_name='Estado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.participante', verbose_name='Participante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
